### PR TITLE
[ARCTIC-1482][Flink]: When making a connection via ams in high availability mode, NoClassDefFoundError is encountered

### LINKED ISSUE #1482: [Bug][Flink]: When making a connection via ams in high availability mode, NoClassDefFoundError is encountered
### What happened?

When I use Flink to connect to ams in high availability mode, Flink SQL execution fails and throws a NoClassDefFoundError.

### Affects Versions

master

### What engines are you seeing the problem on?

Flink

### How to reproduce

SET 'execution.runtime-mode' = 'streaming';
SET 'table.dynamic-table-options.enabled' = 'true';

create catalog arctic_catalog WITH (
    'type'='arctic',
    'metastore.url'='zookeeper://{zookeeper-endpoint-list}/{cluster-name}/{catalog-name}'
);

CREATE TABLE datagen_tb (
    id int,
    user_id int,
    street string
) WITH (
  'connector' = 'datagen',
  'rows-per-second' = '10'
);

insert into arctic_catalog.test.tb
/*+ OPTIONS('streaming'='true','arctic.emit.mode'='log') */
select * from datagen_tb;

create table print_tb (
    id int,
    user_id int,
    street string
) WITH (
    'connector' = 'print'
);

insert into print_tb
select * from arctic_catalog.test.tb
/*+ OPTIONS('streaming'='true','arctic.read.mode'='log', 'scan.startup.mode'='latest') */;

### Relevant log output

```shell
java.lang.NoClassDefFoundError: org/apache/zookeeper/client/ZKClientConfig
    at com.netease.arctic.ams.api.client.ZookeeperService.newClient(ZookeeperService.java:45)
    at com.netease.arctic.ams.api.client.ZookeeperService.<init>(ZookeeperService.java:41)
    at com.netease.arctic.ams.api.client.ZookeeperService.getInstance(ZookeeperService.java:63)
    at com.netease.arctic.ams.api.client.ArcticThriftUrl.parserZookeeperUrl(ArcticThriftUrl.java:123)
    at com.netease.arctic.ams.api.client.ArcticThriftUrl.parse(ArcticThriftUrl.java:65)
    at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:55)
    at com.netease.arctic.flink.InternalCatalogBuilder.createBaseArcticCatalog(InternalCatalogBuilder.java:47)
    at com.netease.arctic.flink.InternalCatalogBuilder.build(InternalCatalogBuilder.java:66)
    at com.netease.arctic.flink.catalog.ArcticCatalog.open(ArcticCatalog.java:105)
    at com.netease.sloth.flink.connector.arctic.catalog.ArcticCatalogWrapper.open(ArcticCatalogWrapper.java:47)
    at org.apache.flink.table.catalog.CatalogManager.registerCatalog(CatalogManager.java:186)
    at com.netease.sloth.flink.sql.catalog.BaseCatalogManagerBuilder.registerCatalog(BaseCatalogManagerBuilder.java:102)
    at com.netease.sloth.flink.sql.catalog.BaseCatalogManagerBuilder.lambda$registerCatalogFromMetahub$1(BaseCatalogManagerBuilder.java:95)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.netease.sloth.flink.sql.catalog.BaseCatalogManagerBuilder.registerCatalogFromMetahub(BaseCatalogManagerBuilder.java:89)
    at com.netease.sloth.flink112.sql.catalog.CatalogManagerBuilder.build(CatalogManagerBuilder.java:102)
    at com.netease.sloth.flink112.sql.table.FlinkTableEnvBuilder.build(FlinkTableEnvBuilder.java:50)
    at com.netease.sloth.flink.sql.planner.SlothJobExecutor.validatorSqlWithoutClassloader(SlothJobExecutor.java:94)
    at com.netease.sloth.flink.sql.api.classload.ClassLoadWrap.execute(ClassLoadWrap.java:70)
    at com.netease.sloth.flink.sql.planner.SlothJobExecutor.validatorSq
```

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lklhdu**
## Why are the changes needed?

fix #1482.
In the same way as pr #1414, the Flink engine needs to include zookeeper and curator-related dependencies when packaging.

## Brief change log

  - *Add zookeeper and curator dependency in flink-runtime pom file*
  - *The flink 1.12 ,1.14 and 1.15 versions are affected.*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by lklhdu** [comment]
> @lklhdu Could update the guide about the `metastore.url` in the Flink section?

thanks for your review, I have completed the update of the documentation section.

**Review by baiyangtx — COMMENTED** [review]
Plz fix the spell problem in spark module

**Comment by lklhdu** [comment]
> Plz fix the spell problem in spark module

ok, I have fixed it.

**Review by YesOrNo828 — APPROVED** [review]
LGTM

**Pull request merged**
