### PR TITLE
[ARCTIC-1367][hive] fix `NullPointerException` for null partition value for Mixed Hive Table

### LINKED ISSUE #1367: [Bug]: Mixed Hive Table's Full Optimizing failed to commit with a value `null` in partition column
### What happened?

For partitioned Mixed Hive Table, Full Optimizing failed to commit when there is a partition with value `null`.

The error message
```
2023-04-19 00:21:04,891 WARN [Metastore Scheduled Commit Worker 9] [com.netease.arctic.ams.server.optimize.BasicOptimizeCommit] [] - Optimize commit table arctic_recsys.appnews.article_attr_model_lake failed, give up commit and clear files in location.
java.lang.NullPointerException: null
        at com.netease.arctic.hive.utils.HivePartitionUtil.partitionValuesAsList(HivePartitionUtil.java:59) ~[arctic-hive-0.4.1-20230417.071014-5.jar:?]
        at com.netease.arctic.hive.op.UpdateHiveFiles.getCreatePartition(UpdateHiveFiles.java:178) ~[arctic-hive-0.4.1-20230417.071014-5.jar:?]
        at com.netease.arctic.hive.op.UpdateHiveFiles.commit(UpdateHiveFiles.java:105) ~[arctic-hive-0.4.1-20230417.071014-5.jar:?]
        at com.netease.arctic.ams.server.optimize.BasicOptimizeCommit.majorCommit(BasicOptimizeCommit.java:361) ~[arctic-ams-server-0.4.1-20230418.065739-4.jar:?]
        at com.netease.arctic.ams.server.optimize.BasicOptimizeCommit.commit(BasicOptimizeCommit.java:145) [arctic-ams-server-0.4.1-20230418.065739-4.jar:?]
        at com.netease.arctic.ams.server.optimize.SupportHiveCommit.commit(SupportHiveCommit.java:129) [arctic-ams-server-0.4.1-20230418.065739-4.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.commitOptimizeTasks(TableOptimizeItem.java:1057) [arctic-ams-server-0.4.1-20230418.065739-4.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCommitWorker.run(OptimizeCommitWorker.java:49) [arctic-ams-server-0.4.1-20230418.065739-4.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

Partition Key
image

null value for Partition
image

### Affects Versions

master/0.3.*,master/0.4.*

### What engines are you seeing the problem on?

_No response_

### How to reproduce

1.create a Mixed Hive Table with partition key `day string`
2.write some data with `day=null`
3.start optimizing for this table
4.when full optimizing is committing, we can see the error message

### Relevant log output

_No response_

### Anything else

It happens every time.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

fix #1367 

## Brief change log

  - fix `NullPointerException` for null partition value for Mixed Hive Table

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by baiyangtx** [comment]
This will make record writen to partition dir with name "null", but in hive, it shoud be writen to "__DEFAULT_PARTITION__"

**Comment by wangtaohz** [comment]
> This will make record writen to partition dir with name "null", but in hive, it shoud be writen to "**DEFAULT_PARTITION**"

I need more details for this design, is there any related issue/PR?

**Comment by baiyangtx** [comment]
> > This will make record writen to partition dir with name "null", but in hive, it shoud be writen to "**DEFAULT_PARTITION**"
> 
> I need more details for this design, is there any related issue/PR?

see this https://www.ibm.com/docs/en/db2-big-sql/5.0.2?topic=dtibs-how-hive-handles-null-values-partitioning-column-type-string

**Comment by zhoujinsong** [comment]
I found related issue below:

- #1085 
- #349 

However, I'm wondering if we could split the related issues into two separate questions:

- Solve the NPE issue caused by empty partition field values, which may affect all table formats.
- Adapt the Mixed-Hive format table, when the partition field value is NULL, you can configure its value to be changed to `__HIVE_DEFAULT_PARTITION__`.

**Comment by wangtaohz** [comment]
> I found related issue below:
> 
> * [[Spark][Bug]: NPE If write to MixedHive Format while partition value is NULL  #1085](https://github.com/NetEase/arctic/issues/1085)
> * [[Feature]: [flink] when partition value is null,  we should write the record to the  partition  default configured. #349](https://github.com/NetEase/arctic/issues/349)
> 
> However, I'm wondering if we could split the related issues into two separate questions:
> 
> * Solve the NPE issue caused by empty partition field values, which may affect all table formats.
> * Adapt the Mixed-Hive format table, when the partition field value is NULL, you can configure its value to be changed to `__HIVE_DEFAULT_PARTITION__`.

It seems to be a long-standing history issue.

For the first question:
However, I haven't fully understood the complexity as @baiyangtx described in #1085, and with this simple PR, it works well for the Mixed hive table in my enviromnent, including writing, minor optimizing, full optimizing. So, I'm not sure how it should affect all other table formats.

For the second one:
I agree the idea with #349, and I think we can open another PR to solve it.

**Comment by zhoujinsong** [comment]
> > I found related issue below:
> > 
> > * [[Spark][Bug]: NPE If write to MixedHive Format while partition value is NULL  #1085](https://github.com/NetEase/arctic/issues/1085)
> > * [[Feature]: [flink] when partition value is null,  we should write the record to the  partition  default configured. #349](https://github.com/NetEase/arctic/issues/349)
> > 
> > However, I'm wondering if we could split the related issues into two separate questions:
> > 
> > * Solve the NPE issue caused by empty partition field values, which may affect all table formats.
> > * Adapt the Mixed-Hive format table, when the partition field value is NULL, you can configure its value to be changed to `__HIVE_DEFAULT_PARTITION__`.
> 
> It seems to be a long-standing history issue.
> 
> For the first question: However, I haven't fully understood the complexity as @baiyangtx described in #1085, and with this simple PR, it works well for the Mixed hive table in my enviromnent, including writing, minor optimizing, full optimizing. So, I'm not sure how it should affect all other table formats.
> 
> For the second one: I agree the idea with #349, and I think we can open another PR to solve it.

#1085 seems to be the same problem as #1367, all is because `HivePartitionUtil.partitionValuesAsList` cannot handle the null value for partition data.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Pull request merged**
