### PR TITLE
[ARCTIC-1356][AMS] Display mandatory status of columns

### PR DESCRIPTION
**Pull request by XBaith**
## Why are the changes needed?
Implementation of #1356 
image

## Brief change log
Display mandatory status of columns on AMS dashboard

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by XBaith** [comment]
cc @zhoujinsong

**Comment by zhoujinsong** [comment]
@XBaith

**Review by shidayang — APPROVED** [review]

**Comment by shidayang** [comment]
LGTM

**Comment by shidayang** [comment]
@XBaith https://github.com/NetEase/arctic/issues/1372 had merged，Could you develop this feature on the new code?

**Review by lpdong — APPROVED** [review]

**Pull request merged**
