### PR TITLE
[ARCTIC-648][AMS] Fix save the field `storage_configs`

### LINKED ISSUE #648: [Bug]: Not saving storage_configs to catalog_metadata correctly when creating a catalog
### What happened?

Not saving storage_configs to catalog_metadata correctly when creating a catalog

### Affects Versions

0.4.0-SNAPSHOT

### What engines are you seeing the problem on?

AMS

### How to reproduce

Create Catalog with
Metastore : Hive Metastore
Table Format : Iceberg

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by zhongqishang**
## Why are the changes needed?

Fix #648 

## Brief change log

Fix save the field `storage_configs`

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zhongqishang** [comment]
@Aireed Please take a look.

**Comment by Aireed** [comment]
> @Aireed Please take a look.

cc @huiyuanz

**Review by huiyuanz — APPROVED** [review]
fix the storageConfig fileName

**Review by Aireed — APPROVED** [review]
LGTM

**Comment by zhoujinsong** [comment]
@huiyuanz @zhongqishang Should we rebuild the frontend code after this change? 
Do you need another PR to submit the files after building？

**Comment by Aireed** [comment]
> 

the rebuild  PR: https://github.com/NetEase/arctic/issues/664

**Pull request merged**
