### PR TITLE
Fix jar conflict

### PR DESCRIPTION
**Pull request by shidayang**
Make ams-api not flat jar

### CODE REVIEW

**Comment by hameizi** [comment]
LGTM

**Review by hameizi — APPROVED** [review]

**Review by zhoujinsong — COMMENTED** [review]
@shidayang I left some comments.
And how should we solve the conflict problem of curator?

**Comment by shidayang** [comment]
@zhoujinsong curator conflict need to shade curator

**Review by zhoujinsong — APPROVED** [review]
LGTM

**Pull request merged**
