### PR TITLE
[ARCTIC-1400] reduce read metadata files times

### PR DESCRIPTION
**Pull request by ZhendongBai**
## Why are the changes needed?

1. improve issue #1400 

## Brief change log
the method read same metadata file twice.

## How was this patch tested?
Test in Local Test environment.

## Documentation

  - Does this pull request introduces a new feature? no

### CODE REVIEW

**Comment by shidayang** [comment]
> LGTM. There is a noticeable improvement in my environment with this patch.
> 
> image

How many metadata files are there in your test scene? I think 9s is also slowly

**Comment by zhoujinsong** [comment]
Should we wait for the [`refactor-ams`](https://github.com/NetEase/arctic/tree/refactor-ams) branch to be merged before merging this PR?

**Comment by wangtaohz** [comment]
> Should we wait for the [refactor-ams](https://github.com/NetEase/arctic/tree/refactor-ams) branch to be merged before merging this PR?

Yes, we could merge it after refactoring ams. And the code in refactor-ams is here
`com.netease.arctic.server.dashboard.ServerTableDescriptor#getTableOperations`

**Comment by wangtaohz** [comment]
> How many metadata files are there in your test scene? The code is LGTM, but I think 9s is slow too. Maybe we should multithread the read

I have 100 metadata files in my test scene.

**Comment by wangtaohz** [comment]
@ZhendongBai Do you have time to resolve the conflict? so that we can merge into the master ASAP

**Comment by wangtaohz** [comment]
LGTM.

**Pull request merged**
