### PR TITLE
[Arctic-1266][AMS]: Use ArcticSparkSessionCatalog for terminal

### LINKED ISSUE #1266: [Improvement]: Support terminal access hive table when switch to a catalog with HMS metastore .
Search before asking

- [x]  I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

What would you like to be improved?

use ArcticSparkSessionCatalog for terminal when user use hive type catalog, then at terminal we run sql for origin hive tables.

How should we improve?

there are few issues need to resolve here:
1. spark session catalog ask to use name 'spark_catalog', and at terminal we maybe need to support multiple hive catalog
2. at sql script, user maybe write the sql with the catalog name.

to resolve these two issue:
1、when setting spark conf befor start terminal session, we can replace the catalog name to spark_catalog.
2、we need to limit the user not contain the catalog name for current catalog at the sql script.

Are you willing to submit PR?
 Yes I am willing to submit a PR!

Subtasks
No response

Code of Conduct
 I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by li36909**
## Why are the changes needed?

Fix  #1266 
Support terminal access hive table when switch to a catalog with HMS metastore 。

## Brief change log

- Use ArcticSparkSessionCatalog for terminal
- Add a config properties to support access hive in terminal.

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
@li36909 Hi, thanks a lot for your PR!
Is there an issue associated with PR?
As this is your first PR for Arctic, I recommend you check out the Community Guide first:
https://github.com/NetEase/arctic/discussions/1216

**Comment by baiyangtx** [comment]
The terminal module is designed to support different backend, we provider 2 default backend, Kyuubi and LocalSpark,  so we can't assume that the backend implement of terminal is Spark.  

I suggest to add addtion properties about catalog type passed to TerminalSessionFactory,  and replace ArcticSparkCatalog to ArcticSparkSessionCatalog in each TerminalSessionFactory implement class.

**Comment by li36909** [comment]
> The terminal module is designed to support different backend, we provider 2 default backend, Kyuubi and LocalSpark, so we can't assume that the backend implement of terminal is Spark.
> 
> I suggest to add addtion properties about catalog type passed to TerminalSessionFactory, and replace ArcticSparkCatalog to ArcticSparkSessionCatalog in each TerminalSessionFactory implement class.

thanks, this change is universal for both spark backend and kyuubi, and if we will use another engine (eg trino) as terminal backend, maybe we can do this at a new pr. 
and I will add a new property for terminal, thanks for you check

**Comment by baiyangtx** [comment]
I suggest to solve this issue in this way.

1.  add a property to terminal configs to force use ArcticSparkSessionCatalog for hive.

```
ams.terminal.backend=local
ams.terminal.local.using-session-catalog-for-hive=true

or
ams.terminal.backend=kyuubi
ams.terminal.kyuubi.using-session-catalog-for-hive=true
```

2.  the TerminalManager already passed the catalog.type to TerminalSessionFactory. so we can replace the ArcticSparkCatalog in the implement class.

Both `KyuubiTerminalSessionFactory` and `LocalTerminalSessionFactory` are using `SparkContextUtil.getSparkConf` to generate the spark configs. Replace the catalog name and implement class here.

```
public static Map<String, String> getSparkConf(Configuration sessionConfig, bool usingSessionCatalogForHive) {
    //.....
   if("iceberg".equal(connector)){
   } else if (sessionConfig.get('type).equal("hive) && usingSessionCatalogForHive) {
       sparkConf.put("spark.sql.catalog." + catalog, ArcticSparkSessionCatalog.class.getName());
        sparkConf.put("spark.sql.catalog." + catalog + ".url", catalogUrlBase + catalog);
   } else {
      //....
  }

}
```

3.  in TerminalSession, ignore `use {catalog}` if current catalog is `spark_catalog`

**Comment by li36909** [comment]
> I suggest to solve this issue in this way.
> 
> 1. add a property to terminal configs to force use ArcticSparkSessionCatalog for hive.
> 
> ```
> ams.terminal.backend=local
> ams.terminal.local.using-session-catalog-for-hive=true
> 
> or
> ams.terminal.backend=kyuubi
> ams.terminal.kyuubi.using-session-catalog-for-hive=true
> ```
> 
> 2. the TerminalManager already passed the catalog.type to TerminalSessionFactory. so we can replace the ArcticSparkCatalog in the implement class.
> 
> Both `KyuubiTerminalSessionFactory` and `LocalTerminalSessionFactory` are using `SparkContextUtil.getSparkConf` to generate the spark configs. Replace the catalog name and implement class here.
> 
> ```
> public static Map<String, String> getSparkConf(Configuration sessionConfig, bool usingSessionCatalogForHive) {
>     //.....
>    if("iceberg".equal(connector)){
>    } else if (sessionConfig.get('type).equal("hive) && usingSessionCatalogForHive) {
>        sparkConf.put("spark.sql.catalog." + catalog, ArcticSparkSessionCatalog.class.getName());
>         sparkConf.put("spark.sql.catalog." + catalog + ".url", catalogUrlBase + catalog);
>    } else {
>       //....
>   }
> 
> }
> ```
> 
> 3. in TerminalSession, ignore `use {catalog}` if current catalog is `spark_catalog`

thanks, I have fix it as this suggestion

**Comment by baiyangtx** [comment]
Tks for your PR,  the code is fine, could please add some tests? or add a local test screenshot in this PR's comment?

**Comment by li36909** [comment]
> Tks for your PR, the code is fine, could please add some tests? or add a local test screenshot in this PR's comment?

thanks, here is my test screenshot:
1. create hive type catalog and arctic catalog
image
2. using hive_catalog to access both origin hive table and mix_hive table
image
image
image
image
image
3. using arctic catalog to access origin hive table, it should fail 
image

**Review by baiyangtx — APPROVED** [review]
LGTM

**Comment by baiyangtx** [comment]
This PR has add a new AMS config property, so could you please update the docs?

**Comment by li36909** [comment]
> This PR has add a new AMS config property, so could you please update the docs?

Added!

**Pull request merged**
