### PR TITLE
[ARCTIC-1489] The Optimizer reports the complete exception stack to AMS

### LINKED ISSUE #1489: [Improvement]: The Optimizer should report the complete exception stack to AMS
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When a task fails to execute, the optimizer only reported simple error message to AMS, which makes it inconvenient to troubleshoot as one needs to check the optimizer's logs.

### How should we improve?

We should report the complete exception stack to AMS.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

fix #1489 

## Brief change log

  - The Optimizer reports the complete exception stack to AMS

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wangtaohz** [comment]
This PR should be cherry-picked to 0.3.x.

**Comment by Aireed** [comment]
I suggest to add hostname to the exception like 'exception from xxxx'. In the production,  we always have a lot of optimizer,  the message can help us locate the exception from quickly.

**Comment by wangtaohz** [comment]
> I suggest to add hostname to the exception like 'exception from xxxx'. In the production, we always have a lot of optimizer, the message can help us locate the exception from quickly.

It's a good suggestion, but I'm a little worried about whether the host is enough to locate where the exception exist, especially when multiple optimizer's threads are running on the same machine, so this may not be a general solution.

And also, the goal of this PR is to avoid users searching logs on the optimizer by reporting complete exception information.

**Comment by wangtaohz** [comment]
> This PR should be cherry-picked to 0.3.x.

I have cherry-picked it to 0.3.x

**Pull request merged**
