### PR TITLE
[ARCTIC-1588] Make hive commit executor enabled

### LINKED ISSUE #1588: [Bug]: Hive commit executor does not enable
### What happened?

HiveCommitSyncExecutor which is responsible for hive sync does not enable.
image

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

Just see the code in com.netease.arctic.server.table.executor.HiveCommitSyncExecutor.

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by HuangFru**
## Why are the changes needed?
Fix #1588.

## Brief change log

  - *Make HiveCommitSyncExecutor enabled to hive table.*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not applicable )

### CODE REVIEW

**Comment by zhoujinsong** [comment]
Thanks a lot for your contribution!

But I noticed the PR's title did not match the community requirement, you can find the the community guilds here:https://docs.google.com/document/d/1Pwv1LflW3z5yq34qDpEYwSxOB3LIE5qoKQ_5Sv0IV1Y/edit?usp=sharing

**Comment by HuangFru** [comment]
> Thanks a lot for your contribution!
> 
> But I noticed the PR's title did not match the community requirement, you can find the the community guilds here:https://docs.google.com/document/d/1Pwv1LflW3z5yq34qDpEYwSxOB3LIE5qoKQ_5Sv0IV1Y/edit?usp=sharing

I made an oversight, already been fixed.

**Review by zhoujinsong — APPROVED** [review]

**Comment by wangtaohz** [comment]
After merging this PR, the AMS will hand up when starting. @HuangFru 
image

**Comment by HuangFru** [comment]
> 

Looks like I should set the `enabled` method in HiveCommitSyncExecutor always to `true` and check if it's needed in `execute`.

**Comment by wangtaohz** [comment]
> Looks like I should set the enabled method in HiveCommitSyncExecutor always to true and check if it's needed in execute.

Can you submit another PR to address this issue? I believe it is easily reproducible and critical.

**Comment by HuangFru** [comment]
> 
Yes, I'm doing it.

**Pull request merged**
