### PR TITLE
[ARCTIC-362][AMS]add schema sql file for every version for ams

### LINKED ISSUE #362: [Improvement][AMS]:add schema sql file for every version for ams
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?page=4&q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

add schema sql file for every version for ams 

### How should we improve?

add schema sql file for every version for ams 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hameizi**
## Why are the changes needed?
resolve #362 

## Brief change log
add schema sql file for every version for ams

## How was this patch tested?
test procedures:
1. use `0.3.0-init.sql` and `upgrade-sql` to database1. exec `mysql -h {mysql_host} -P {mysql_port} -u {user} -p {password} database1 < {AMS_HOME_DIR}/conf/mysql/0.3.0-init.sql` and `mysql -h {mysql_host} -P {mysql_port} -u {user} -p {password}database1 < {AMS_HOME_DIR}/conf/mysql//upgrade-0.3.0-to-0.3.1.sql`
2. use `0.3.1-init.sql` to database2. exec `mysql -h {mysql_host} -P {mysql_port} -u {user} -p {password} database2 < {AMS_HOME_DIR}/conf/mysql/0.3.1-init.sql`
3. Check whether the schemas of database1 and database2 are the same.

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (docs)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
@hameizi Hi，have you test the SQL script on your local envrionment to verify its correctness.

**Comment by hameizi** [comment]
> @hameizi Hi，have you test the SQL script on your local envrionment to verify its correctness.

yes, test 0.3.1-init.sql and 0.3.0-init.sql&upgrade-0.3.0-to-0.3.1.sql.

**Comment by zhoujinsong** [comment]
> > @hameizi Hi，have you test the SQL script on your local envrionment to verify its correctness.
> 
> yes, test 0.3.1-init.sql and 0.3.0-init.sql&upgrade-0.3.0-to-0.3.1.sql.

Okay, so you may choose the wrong option of your `How was this patch tested` in PR description?

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Comment by hameizi** [comment]
> > > @hameizi Hi，have you test the SQL script on your local envrionment to verify its correctness.
> > 
> > 
> > yes, test 0.3.1-init.sql and 0.3.0-init.sql&upgrade-0.3.0-to-0.3.1.sql.
> 
> Okay, so you may choose the wrong option of your `How was this patch tested` in PR description?

done

**Pull request merged**
