### PR TITLE
[ARCTIC-1611] Fix Preconditions import

### LINKED ISSUE #1611: [Bug]For flinkcontainer optimizer, When making a connection via ams in high availability mode, NoSuchMethodError is encountered
### What happened?

When use flink job as optimizer ,and  making a connection via ams in high availability mode, NoClassDefFoundError is encountered

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

Optimizer

### How to reproduce

ams  high availability mode
use flink job as optimizer 
flink 1.12
flink parameter
`-hb 60000 -p 1 -a zookeeper://{zookeeper-endpoint-list} -g{OPTIMIZER_GROUP_NAME} -m{OPTIMIZER_MEMORY}`

### Relevant log output

```shell
2023-06-26 15:08:59,941 INFO  com.netease.arctic.optimizer.OptimizerToucher                [] - Starting optimizer toucher with configuration:OptimizerConfig{amsUrl=zookeeper://10.105.5.84:2181/arctic-xieyi-test, executionParallel=1, memorySize=2048, groupName=analysis_xieyi_external, heartBeat=60000, extendDiskStorage=false, rocksDBBasePath=null, memoryStorageSize=512, resourceId=null}
2023-06-26 15:08:59,947 INFO  org.apache.flink.runtime.io.network.partition.consumer.SingleInputGate [] - Converting recovered input channels (1 channels)
2023-06-26 15:09:00,063 ERROR com.netease.arctic.optimizer.AbstractOptimizerOperator       [] - Call ams got an error and will try again later
java.lang.NoSuchMethodError: org.apache.zookeeper.server.quorum.flexible.QuorumMaj.<init>(Ljava/util/Map;)V
	at org.apache.curator.framework.imps.EnsembleTracker.<init>(EnsembleTracker.java:57) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:187) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:188) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ZookeeperService.newClient(ZookeeperService.java:65) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ZookeeperService.<init>(ZookeeperService.java:41) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ZookeeperService.getInstance(ZookeeperService.java:48) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ArcticThriftUrl.parserZookeeperUrl(ArcticThriftUrl.java:135) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ArcticThriftUrl.parse(ArcticThriftUrl.java:77) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ThriftClientPool$1.create(ThriftClientPool.java:96) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ThriftClientPool$1.create(ThriftClientPool.java:90) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:69) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ThriftClientPool.iface(ThriftClientPool.java:218) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.OptimizingClientPools.getClient(OptimizingClientPools.java:41) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.optimizer.AbstractOptimizerOperator.callAms(AbstractOptimizerOperator.java:33) [arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.optimizer.OptimizerToucher.checkToken(OptimizerToucher.java:55) [arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.optimizer.OptimizerToucher.start(OptimizerToucher.java:41) [arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkToucher.run(FlinkToucher.java:45) [arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist_2.12-ne-flink-1.12.4-1.1.7.1.jar:ne-flink-1.12.4-1.1.7.1]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66) [flink-dist_2.12-ne-flink-1.12.4-1.1.7.1.jar:ne-flink-1.12.4-1.1.7.1]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:263) [flink-dist_2.12-ne-flink-1.12.4-1.1.7.1.jar:ne-flink-1.12.4-1.1.7.1]
```
```


### Anything else

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by HuangFru**
## Why are the changes needed?
Fix what I mentioned in #1611.

## Brief change log

  - *Change `Preconditions` to Iceberg relocated.*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by HuangFru** [comment]
> This PR could fix the related issue? It seems not the reason for the bug.

This could fix what I encountered mentioned in the issue.

**Review by baiyangtx — APPROVED** [review]
LGTM

**Comment by wangtaohz** [comment]
There are still some imports of `org.apache.curator.shaded.com.google.common.*` in the project.
I think they can be changed to `org.apache.iceberg.relocated.com.google.common.*` in this PR to avoid potential problems.

**Comment by HuangFru** [comment]
> There are still some imports of `org.apache.curator.shaded.com.google.common.*` in the project. I think they can be changed to `org.apache.iceberg.relocated.com.google.common.*` in this PR to avoid potential problems.

Agree, I'll do it.

**Comment by HuangFru** [comment]
Also, fix a small compatibility bug.

**Review by wangtaohz — APPROVED** [review]
LGTM

**Pull request merged**
