### PR TITLE
Replace the keyword base to others: abstract, basic

### PR DESCRIPTION
**Pull request by YesOrNo828**
## Why are the changes needed?

Fix: #1082 

## Brief change log

  - *Rename core and hive module class name, replace the keyword base to others*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable

### CODE REVIEW

**Review by zhoujinsong — COMMENTED** [review]
LGTM.
Besides, should we change the `BaseArcticCatalog` and `BaseIcebergCatalog` too?

**Comment by YesOrNo828** [comment]
> LGTM. Besides, should we change the `BaseArcticCatalog` and `BaseIcebergCatalog` too?

@zhoujinsong  Please take a look, followed up below classes:
AbstractArcticOptimizePlan.java
AbstractIcebergOptimizePlan.java
AbstractOptimizePlan.java
BasicArcticCatalog.java
BasicIcebergCatalog.java
ChangeTableBasicIncrementalScan.java
AbstractExecutor.java
TestBasicArcticCatalog.java

**Comment by wangtaohz** [comment]
I also find some other Classes could be changed:
- `BaseOptimizeTask` -> `BasicOptimizeTask`
- `BaseOptimizeTaskRuntime` -> `OptimizeTaskRuntime`
- `BaseOptimizeCommit` -> `CommonOptimizeCommit`

**Comment by zhoujinsong** [comment]
> I also find some other Classes could be changed:
> 
> * `BaseOptimizeTask` -> `BasicOptimizeTask`
> * `BaseOptimizeTaskRuntime` -> `OptimizeTaskRuntime`
> * `BaseOptimizeCommit` -> `CommonOptimizeCommit`
> 
> I refactor with this [YesOrNo828#1](https://github.com/YesOrNo828/arctic/pull/1).
> 
> Please take a look @YesOrNo828

What is the principle of using different prefixes like `Basic` or `Common`?

**Comment by zhoujinsong** [comment]
> > LGTM. Besides, should we change the `BaseArcticCatalog` and `BaseIcebergCatalog` too?
> 
> @zhoujinsong Please take a look, followed up below classes: AbstractArcticOptimizePlan.java AbstractIcebergOptimizePlan.java AbstractOptimizePlan.java BasicArcticCatalog.java BasicIcebergCatalog.java ChangeTableBasicIncrementalScan.java AbstractExecutor.java TestBasicArcticCatalog.java

They are look good to me.

**Comment by YesOrNo828** [comment]
> What is the principle of using different prefixes like `Basic` or `Common`?

As far as I can see:

"Basic" often refers to something that is fundamental, simple, or stripped down to its core elements. For example, a "basic" version of a software program might have fewer features than the full version, or a "basic" course might cover only the essential topics.

"Common" typically refers to something that is widely shared, used, or found across different situations. For example, a "common" feature of several different software programs might be a user interface that is easy to navigate, or a "common" practice in a particular field might be to use a specific type of data analysis tool.

**Comment by zhoujinsong** [comment]
> > What is the principle of using different prefixes like `Basic` or `Common`?
> 
> As far as I can see:
> 
> "Basic" often refers to something that is fundamental, simple, or stripped down to its core elements. For example, a "basic" version of a software program might have fewer features than the full version, or a "basic" course might cover only the essential topics.
> 
> "Common" typically refers to something that is widely shared, used, or found across different situations. For example, a "common" feature of several different software programs might be a user interface that is easy to navigate, or a "common" practice in a particular field might be to use a specific type of data analysis tool.

According to the description, is the `BasicOptimizeCommit` better than `CommonOptimizeCommit` as it has several sub implementations?

**Comment by wangtaohz** [comment]
> According to the description, is the BasicOptimizeCommit better than CommonOptimizeCommit as it has several sub implementations?

I agree with that. But I suggest modifying it with another PR.

**Review by wangtaohz — APPROVED** [review]

**Pull request merged**
