### PR TITLE
[ARCTIC-1319] [ams] Major Self-Optimizing should not delete pos-delete files

### LINKED ISSUE #1319: [Bug]: Some deleted records came back after Self-Optimizing for the KeyedTable
### What happened?

I have a KeyedTable(Mixed Hive Format) with a flink job writing into it.

I find some deleted records came back after Major Self-Optimizing, breaking the data consistency.

### Affects Versions

master/0.3.*,master/0.4.*

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. create a KeyedTable(Mixed Hive/Iceberg Format)
2. insert overwrite some records into the Base Store, including the record id = 1, making these files' size > 16M
3. disable Self-Optimizing
4. update record id = 1 (Change Store)
5. update record id = 1 (Change Store)
6. delete record id = 1 (Change Store)
7. enable Self-Optimizing
8. After Minor Optimizing and Major Optimizing, select by MOR, and the record id = 1 could be found from the result, which is expected to be deleted

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

fix #1319 

## Brief change log

  - Major Self-Optimizing should not delete pos-delete files

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by wangtaohz** [comment]
We should cherry-pick this PR to 0.3.x

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Comment by zhoujinsong** [comment]
> We should cherry-pick this PR to 0.3.x

When I try to cherry-pick this PR into branch 0.3.x, it caused some conflicts in the unit test codes.
So I am wondering if we need to fix this bug in another PR for branch 0.3.x.

**Comment by wangtaohz** [comment]
> > We should cherry-pick this PR to 0.3.x
> 
> When I try to cherry-pick this PR into branch 0.3.x, it caused some conflicts in the unit test codes. So I am wondering if we need to fix this bug in another PR for branch 0.3.x.

OK, I will open another PR for 0.3.x.

**Comment by zhoujinsong** [comment]
Cherry-picked into branch 0.4.x.

**Pull request merged**
