### PR TITLE
[ARCTIC-1691] Fix file count/size and quota occupation is `0` when in pending optimizing status

### LINKED ISSUE #1691: [Bug]: The file count/size and quota occupation are `0` when optimizing status is pending
### What happened?

The file count and size should not be `0` when table is in pending status
image

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. create an table
2. not start any optimizer
3. insert some record into the table
4. wait for 1min, the table's optimizing status will be pending, and the file count and file size are `0`

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

fix #1691 

## Brief change log

  - get file count and size from `pendingInput` when optimizing status is ending
  - fix quota occupation is zero
  - persist pending_input into sysdb
  - rename JsonSummaryConverter to JsonObjectConverter

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by wangtaohz** [comment]
image

**Comment by zhoujinsong** [comment]
I am considering the necessity of storing PendingInput in the system database. With the optimizing plan process to upgrade, PendingInput is highly likely to undergo frequent structural changes, which may bring compatibility risks with old data. 

In my opinion, PendingInput itself is designed to optimize the planning process. It is not necessary to persist. In other words, when AMS restarts, it may be more appropriate for the table in the original Pending state to directly enter the Idle state.

**Comment by wangtaohz** [comment]
I am just trying to fix an edge case where the file size/count in Pending status becomes 0 after restarting AMS. Even worse, in this situation, `pendingInput` will remain 0 if there are no new writes to the table.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Pull request merged**
